### ISSUE TITLE
Pre-trained models for other datasets

### ISSUE THREAD

**Issue by samiarja** [Jyxarthur/OCLR_model#2]
Thanks for providing the flow-only OCLR model for syn data.
Do you have the pre-trained models for other datasets like DAVIS2016, DAVIS2017-motion, SegTrackv2, FBMS-59 and MoCA_filter etc.?

**Comment by Jyxarthur** [comment]
Thanks for your interest in our work. Our model is synthetically trained and can be generalized to real-world datasets. Therefore, the synthetically trained model checkpoint can be directly applied to real-world video datasets.
